### ISSUE TITLE
tm_deploy error

### ISSUE THREAD

**Issue by pampernickel** [TissueMAPS/TissueMAPS#68] opened 2017-08-31 20:31 UTC
Following instructions for TM installation (on ScienceCloud) of tmdeploy 0.3.3, issuing the tm_deploy -vv vm launch command results in the following error:

>Traceback
 (most recent call last):
  File "/home/ubuntu/.local/bin/tm_deploy", line 4, in <module>
    __import__('pkg_resources').require('tmdeploy==0.3.3rc0')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.11.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('requests>=2.14.2'), set(['python-ironicclient', 'python-keystoneclient', 'keystoneauth1']))

I've tried to resolved by following the trace of dependencies (uninstalling and reinstalling python-keystoneclient), but nothing has worked so far. Would be great to know what's going on, and how I can resolve this. Thanks!

**Comment by riccardomurri** [comment] 2017-08-31 20:41
Hello @pampernickel can you please run the following command at the same terminal prompt where you run `tm_deploy` and post the result here?

     fgrep 'Requires-Dist: requests' /usr/local/lib/python2.7/dist-packages/*.dist-info/METADATA

**Comment by pampernickel** [comment] 2017-08-31 20:45
/usr/local/lib/python2.7/dist-packages/docker-2.5.1.dist-info/METADATA:Requires-Dist: requests (>=2.5.2,!=2.12.2,!=2.11.0,!=2.18.0)
/usr/local/lib/python2.7/dist-packages/docker_py-1.10.6.dist-info/METADATA:Requires-Dist: requests (>=2.5.2,!=2.11.0)
/usr/local/lib/python2.7/dist-packages/python_keystoneclient-3.13.0.dist-info/METADATA:Requires-Dist: requests (>=2.14.2)

**Comment by riccardomurri** [comment] 2017-08-31 20:54
Can you please try re-installing TmDeploy from the source repository? ("master" branch, commit e48b462 or later)

After re-installing, if the problem persists, please run the following command::

    pip uninstall ansible-container docker-compose docker-py

**Comment by pampernickel** [comment] 2017-09-03 20:53
Tried this; I'm now able to get further:

`tm_deploy -vv vm launch
2017-09-03 20:43:25 | INFO     | tm_deploy                                | launch virtual machines
2017-09-03 20:43:25 | INFO     | tm_deploy                                | run Ansible commands
`

but I then get this error message:

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tm_inventory", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/TmDeploy/bin/tm_inventory", line 359, in <module>
    main(args)
  File "/home/ubuntu/TmDeploy/bin/tm_inventory", line 295, in main
    setup = Setup(setup_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/config.py", line 765, in __init__
    description = self._load_description(setup_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/config.py", line 783, in _load_description
    description = read_yaml_file(description_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/utils.py", line 55, in read_yaml_file
    return yaml.load(f)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/home/ubuntu/.tmaps/setup/setup.yml", line 35, column 1
Using /home/ubuntu/TmDeploy/tmdeploy/share/playbooks/tissuemaps/ansible.cfg as config file
ERROR! Attempted to execute "/home/ubuntu/.local/bin/tm_inventory" as inventory script: Inventory script (/home/ubuntu/.local/bin/tm_inventory) had an execution error: Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tm_inventory", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/TmDeploy/bin/tm_inventory", line 359, in <module>
    main(args)
  File "/home/ubuntu/TmDeploy/bin/tm_inventory", line 295, in main
    setup = Setup(setup_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/config.py", line 765, in __init__
    description = self._load_description(setup_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/config.py", line 783, in _load_description
    description = read_yaml_file(description_file)
  File "/home/ubuntu/TmDeploy/tmdeploy/utils.py", line 55, in read_yaml_file
    return yaml.load(f)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/home/ubuntu/.tmaps/setup/setup.yml", line 35, column 1`

I uninstalled ansible-container, docker-compose and docker-py as you suggested, but still get the same error. I'm triple-checking my setup.yml against the error, but you might spot what's wrong faster than I do. Thanks.

**Comment by riccardomurri** [comment] 2017-09-04 04:35
Hello,

So the dependency issue seems fixed.

Now the new error you're getting seems related to the fact that there are
TAB characters in the `setup.yml` configuration file which you created. Can
you please configure your text editor to only use spaces and avoid TABs?

If you do not know how to do that, the following commands do the conversion:

```
expand ~/tmaps/setup/setup.yml > /tmp/setup.yml;
mv /tmp/setup.yml ~/tmaps/setup/setup.yml
```

(That's two lines.)

Let us know how it goes.

Il 03 set 2017 10:53 PM, "Pam Dobay" <notifications@github.com> ha scritto:

**Comment by pampernickel** [comment] 2017-09-04 05:21
Strange, was using vi and spaces -- but was able to convert it. I'm now getting minor errors, for which I'd go through my config for fixes:

`2017-09-04 05:19:08 | INFO     | tm_deploy                                | launch virtual machines
2017-09-04 05:19:08 | INFO     | tm_deploy                                | run Ansible commands
2017-09-04 05:19:08 | ERROR    | tm_inventory                             | Environment variable "OS_PROJECT_NAME" must be set for "os" provider.
Using /home/ubuntu/TmDeploy/tmdeploy/share/playbooks/tissuemaps/ansible.cfg as config file
ERROR! Attempted to execute "/home/ubuntu/.local/bin/tm_inventory" as inventory script: Inventory script (/home/ubuntu/.local/bin/tm_inventory) had an execution error: 2017-09-04 05:19:09 | ERROR    | tm_inventory                             | Environment variable "OS_PROJECT_NAME" must be set for "os" provider.
`

Thanks!

**Comment by hackermd** [comment] 2017-09-04 06:14
You need to set your cloud credentials in form of environment variables, see http://docs.tissuemaps.org/latest/installation.html#credentials

**Comment by pampernickel** [comment] 2017-09-04 08:32
Yes, I realized this, as the issue was with .openstack.rc, working on it

**Comment by pampernickel** [comment] 2017-09-04 08:50
Will try again later once the issues with ScienceCloud(?) are resolved. Gotten past the previous error, but now I get a connection error:

`keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to https://cloud.s3it.uzh.ch:5000/v2.0/tokens: HTTPSConnectionPool(host='cloud.s3it.uzh.ch', port=5000): Max retries exceeded with url: /v2.0/tokens (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe0bb518690>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Using /home/ubuntu/TmDeploy/tmdeploy/share/playbooks/tissuemaps/ansible.cfg as config file`

Will keep you updated on this once I can connect again to ScienceCloud

**Comment by hackermd** [comment] 2017-09-04 09:54
You can also deploy on AWS if you don't want to wait. Just note that a freetier machine type won't be enough.

**Comment by pampernickel** [comment] 2017-09-04 18:01
I need to fix the image specs on my setup.py -- looks like everything else worked, but I get the ff warning:
`2017-09-04 17:55:10 | WARNING  | tm_inventory | no instance found for host "tm-standalone-server-001"`

Here, I used the ubuntu image specs that I'm using (Ubuntu 16.04 (2017-07-18) + python2.7 + R (2016-10-21)); I've also tried the specs on the installation cheat sheet (Ubuntu Server 16.04.01 LTS + python2.7 + R(2016-10-21)), but am getting the same issue. This is really not my expertise (but I want to try to get it to run, so that I can help my colleagues with it in the future), so please bear with me. Thanks!

**Comment by hackermd** [comment] 2017-09-04 18:05
This warning is generated by the dynamic inventory which cannot find the given instance in the cloud registry (yet). Since you are just creating the instance, it does not yet exist. I agree that the message might be a bit confusing at this stage.

**Comment by pampernickel** [comment] 2017-09-04 19:22
Going through the thread, I see that there was, in fact, an error:
`fatal: [tm-standalone-server-001 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find image Ubuntu 16.04 (2017-07-18) + python 2.7 + R (2016-10-21)"}`

My image flavor is Ubuntu 16.04 (2017-07-18);  if I change it to the specs indicated in the cheat sheet:
Ubuntu Server 16.04.01 LTS + python2.7 + R(2016-10-21)

I get the same:
`fatal: [tm-standalone-server-001 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find image Ubuntu 16.04.1 LTS + python 2.7 + R (2016-10-21)"}`

Which is the reason that the instance doesn't exist. What am I doing wrong here?

**Comment by hackermd** [comment] 2017-09-04 19:25
The problem is not the VM instance. It seems that the image `Ubuntu 16.04.1 LTS + python 2.7 + R (2016-10-21)` does not exist. You you try another public image? Python and R will both automatically get installed by tmdeploy.

**Comment by pampernickel** [comment] 2017-09-04 19:36
Yes, in fact, what I tried first was Ubuntu 16.04 (2017-07-18), which is the flavor of the instance I'm running

**Comment by jluethi** [comment] 2017-09-05 12:52
@pampernickel The "Ubuntu 16.04 (2017-07-18) + python 2.7 + R" image is a local image in the pelkmanslab that we used in the past. It will thus not exist in your science cloud tenant.
To me, the error message look like it couldn't get a virtual machine from Science cloud. This will always happen for the "Ubuntu 16.04 (2017-07-18) + python 2.7 + R" image (as it doesn't exist in your tenant) and probably with the "Ubuntu 16.04 (2017-07-18)" you were unlucky because Science cloud was down Friday evening - Monday evening. I would try again using "Ubuntu 16.04 (2017-08-25)" (as this contains most of the system updates already) or "Ubuntu 16.04 (2017-07-18)" (as this is certainly present in your tenant).

**Comment by pampernickel** [comment] 2017-09-05 13:16
@jluethi, will try both Ubuntu 16.04 (2017-07-18) again and Ubuntu 16.04 (2017-08-25) (this was what I tried first, as this is what I have as an instance, but I nonetheless gave the Ubuntu 16.04.1 LTS when I didn't work).

**Comment by pampernickel** [comment] 2017-09-05 22:26
Still an error (Ubuntu 16.04 (2017-07-18) + python 2.7 + R (2016-10-21)):
`fatal: [tm-standalone-server-001 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find image Ubuntu 16.04 (2017-07-18) + python 2.7 + R (2016-10-21)"}`

as well as with Ubuntu 16.04 (2017-08-25):
`fatal: [tm-standalone-server-001 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find image Ubuntu 16.04 (2017-08-25) + python 2.7 + R (2016-10-21)"}`

**Comment by riccardomurri** [comment] 2017-09-06 05:15
@pampernickel Can you please run these commands and post the output?

    echo OS_PROJECT_NAME=$OS_PROJECT_NAME
    echo OS_TENANT_NAME=$OS_TENANT_NAME
    openstack image list

**Comment by pampernickel** [comment] 2017-09-06 06:50
`echo OS_PROJECT_NAME=$OS_PROJECT_NAME
OS_PROJECT_NAME=bioinformatics.kispi.usz
echo OS_TENANT_NAME=$OS_TENANT_NAME
OS_TENANT_NAME=
openstack image list
+--------------------------------------+-------------------------------------------------------+--------+
| ID                                   | Name                                                  | Status |
+--------------------------------------+-------------------------------------------------------+--------+
| 8614580f-d77d-4db8-a7e6-176d0dcc33e5 | CentOS 6.9 (2017-07-18)                               | active |
| 59dd207a-f5f2-41f6-ad0e-7da6887e8938 | CentOS 6.9 (2017-08-25)                               | active |
| da9eea76-98e5-4d18-812b-10e155dfec8d | CentOS 7.3.1611 (2017-07-18)                          | active |
| 8fe0692f-07ee-41d6-b297-6d8a9a1344a7 | CentOS 7.3.1611 (2017-08-25)                          | active |
| 90fc03e3-6c68-4744-9c3b-d779f33b13dd | Debian 8.8 (2017-06-21)                               | active |
| 36124742-89ae-4bfd-8c62-a62affb559e2 | Debian 8.9 (2017-08-25)                               | active |
| c2536eaa-e30d-4a0c-ab61-383fdd275856 | Debian 9.0 (2017-06-21)                               | active |
| 5cf75770-590c-4de2-814b-c59fb1109d16 | Debian 9.1 (2017-08-25)                               | active |
| ba6e6689-3f31-41f4-a575-9b36f416f5f0 | Gaussian G09 D.01 (2016-08-30)                        | active |
| c0cd43e6-c1b8-4d68-b831-2628269f0113 | Mathematica 11 - ubuntu 16.04 x86_64 - (2016-08-18)   | active |
| bed3bbf1-b64e-4458-805e-2a5aaca3907a | Matlab-R2015b - ubuntu 14.04.4 x86-64 - (2016-02-17)  | active |
| 887bb081-a5ad-4d48-9e2b-8b126accc539 | Matlab-R2016a - ubuntu 14.04.4 x86-64 - (2016-03-17)  | active |
| 6e159f76-4119-44c8-b67c-253c8833b05e | Matlab-R2016b - ubuntu 16.04.1 (2016-11-02)           | active |
| a16eb1e0-c416-4219-85e4-ec4886adb100 | PAML 4.9b (2016-11-04)                                | active |
| 2a7a2c1a-76a7-4174-9116-4aa8799347ac | Ubuntu 14.04 (2017-07-18)                             | active |
| e5ebc0c4-eb61-4ec0-af80-b93e4e8bf1e0 | Ubuntu 14.04 (2017-08-25)                             | active |
| 944742b4-9664-4c5e-845e-74a6d1220dbe | Ubuntu 16.04 (2017-07-18)                             | active |
| df5db8b6-06de-4cf5-9c4b-e513d0c510d1 | Ubuntu 16.04 (2017-08-25)                             | active |
| c0a006d1-1734-4b8d-abe8-ed302b50c0f0 | Windows Server 2012 R2 Standard - x86_64 (2017-01-09) | active |
+--------------------------------------+-------------------------------------------------------+--------+
`

**Comment by jluethi** [comment] 2017-09-06 07:02
The issue is with the image name. There was a misunderstanding: You do not need the "+ python 2.7 + R (2016-10-21)" part of the image name. That was part of an image name specific to the Pelkmans lab. For your Science Cloud instance, you want to start an image just called "Ubuntu 16.04 (2017-08-25)" (no additions).

**Comment by pampernickel** [comment] 2017-09-06 08:05
@jluethi, I'm trying this later on a dedicated instance. I wanted to launch an instance from inside another, but of course I'm running into RAM quota issues. Will keep you posted, but it looks like it will work this time. Thanks!

**Comment by riccardomurri** [comment] 2018-08-22 08:48
Closing since no updates in about a year.

**Closed by riccardomurri** 2018-08-22 08:48 UTC
