### ISSUE TITLE
Classification cannot be done due to the lack of avalible memory on the TM machine/memory needed is wrongly estimated by the TM

### ISSUE THREAD

**Issue by maffka123** [TissueMAPS/TissueMAPS#105] opened 2017-12-12 07:56 UTC
Classification on TM never runs through.
There is no problem submitting it:
<img width="1327" alt="bildschirmfoto 2017-12-09 um 20 30 54" src="https://user-images.githubusercontent.com/19744910/33873004-a3e90d92-df19-11e7-9fb6-80bbe15f303f.png">
But then this task is stuck forever in the DB in state 'NEW'.
The general complain in the log that there is not enough avalible memory. Tried to modify gc3pie.conf and allocate 10 Gb per core. The error got:
>         | Got error in submitting task '114972', informing scheduler:
>         LRMSSubmitError: Resource localhost does not have enough available memory:
>         20000MB requested, but only 10000MB available._

After changing avaliable memory to 21 Gb, got:
>         | Got error in submitting task '114973', informing scheduler:
>         LRMSSubmitError: Resource localhost does not have enough available memory:
>         42000MB requested, but only 21000MB available._

**Additional info:**

        tissuemaps@tmmasha-standalone-server-001:~/tmlibrary$ git rev-parse HEAD
        c0720109ba9d82f5e1d155b330a0462f7fc3d8b6
        tissuemaps@tmmasha-standalone-server-001:~/tmlibrary$ git status
        On branch master
        Your branch is up-to-date with 'origin/master'.
        nothing to commit, working directory clean

        tissuemaps@tmmasha-standalone-server-001:~/tmserver$ git rev-parse HEAD
        40fe6cf642b8810cd1f6f40b96f10dd8fed27ef7
        tissuemaps@tmmasha-standalone-server-001:~/tmserver$ git status
        On branch master
        Your branch is up-to-date with 'origin/master'.
        nothing to commit, working directory clean

gc3pie.conf:
```
[auth/noauth]
type=none

[resource/localhost]
enabled=true
type=shellcmd
spooldir=/var/tmp
transport=local
auth=noauth
architecture=x64_64
max_cores=32
max_cores_per_job=2
max_memory_per_core=21 GB
max_walltime=48 hours
override=no

[resource/cluster]
enabled=false
type=slurm
frontend=tmmasha-standalone-server-001
transport=local
auth=noauth
architecture=x86_64
max_cores=2
max_cores_per_job=2
max_memory_per_core=875 MB
max_walltime=10 days
```

**Comment by riccardomurri** [comment] 2017-12-12 17:19
Can you please post the output of the following two blocks of commands (as
user `tissuemaps`)::

    cd ~/tmlibrary
    git rev-parse HEAD
    git status

    cd ~/tmserver
    git rev-parse HEAD
    git status                                                                                                                                                

Also please share the contents of your `gc3pie.conf` file. (Here or by private email)

**Comment by maffka123** [comment] 2017-12-13 10:26
Sorry, I forgot.
Now I adited all this to the error description

**Comment by riccardomurri** [comment] 2017-12-13 14:39
I think the problem is in lines 84--89 of file
`tmlibrary/tools/manager.py`::

```python
    def create_job(self, submission_id, user_name, duration='06:00:00',
            memory=(
                cfg.resource.max_cores_per_job *
                cfg.resource.max_memory_per_core.amount(Memory.MB)
            ),
            cores=cfg.resource.max_cores_per_job):
```

A job is submitted using a multiple of the max memory per core.
(Since you have `max_cores=2` then you get double the value.)

**Comment by riccardomurri** [comment] 2017-12-13 14:43
This is related to the misunderstanding in https://github.com/uzh/gc3pie/issues/624 and needs basically the same fix as https://github.com/TissueMAPS/TmLibrary/pull/39

**Comment by riccardomurri** [comment] 2017-12-13 20:25
This should be fixed by the code in PR https://github.com/TissueMAPS/TmLibrary/pull/39 -- can you please check?

**Comment by maffka123** [comment] 2017-12-15 10:47
The fix in the TmLibrary helped! Thanks a lot!

**Closed** 2017-12-18 09:09 UTC
