### ISSUE TITLE
jterator interface: source code not visible

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#102] opened 2017-11-23 11:58 UTC
It used to be possible to inspect the source code from the jterator interface. This now gives a popup with an error message. All modules appear the same.

![screen shot 2017-11-23 at 12 57 25](https://user-images.githubusercontent.com/5407848/33171803-fd3ac78a-d04d-11e7-9361-67c944a01f20.png)

**Comment by jluethi** [comment] 2017-11-24 15:08
I can't reproduce this in a v0.3.3 machine. @scottberry what jtlibrary version are you using?

**Comment by scottberry** [comment] 2017-11-24 15:25
current develop branch, with a few extra modifications of my own: https://github.com/scottberry/JtLibrary/tree/scottberry-rebase <https://github.com/scottberry/JtLibrary/tree/scottberry-rebase>

**Comment by riccardomurri** [comment] 2018-08-22 14:26
This is fixed in the current "master" branch (commit 1913c410e and bug fixes thereof).

**Closed by riccardomurri** 2018-08-22 14:26 UTC
